#!/usr/bin/env python3

from __future__ import annotations

import argparse
import math
import shutil
import subprocess
import sys
from pathlib import Path

__author__ = "Liao Herui"

USAGE = "VirStrain - An RNA virus strain-level identification tool for short reads."


def run_cmd(cmd: list[str], stdout_path: Path | None = None) -> None:
    """
    Run a command and raise an exception if it fails.
    Optionally redirect stdout to a file.
    """
    if stdout_path is not None:
        with stdout_path.open("w", encoding="utf-8") as out_handle:
            subprocess.run(cmd, check=True, stdout=out_handle)
    else:
        subprocess.run(cmd, check=True)


def scan_msa(in_msa: Path) -> tuple[int, int]:
    """
    Scan an MSA FASTA file and return:
    - number of sequences
    - number of columns (length of first sequence)
    """
    dseq: dict[str, str] = {}
    current_name: str | None = None

    with in_msa.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith(">"):
                current_name = line
                dseq[current_name] = ""
            else:
                if current_name is None:
                    raise ValueError(f"Sequence found before FASTA header in {in_msa}")
                dseq[current_name] += line

    if not dseq:
        raise ValueError(f"No sequences found in MSA file: {in_msa}")

    cnum = len(next(iter(dseq.values())))
    return len(dseq), cnum


def manual_covering(sitec: float, snum: int, in_msa: Path, site_r: tuple[int, int]) -> None:
    """
    Add manually covered sites based on entropy output.
    """
    manual_column = Path("manual.column")
    mc_column = Path("mc.column")
    virstrain_build_column = Path("VirStrain_build.column")
    virstrain_build_temp = Path("VirStrain_build_tem.column")

    run_cmd(
        ["perl", "bin/aln2entropy.pl", str(in_msa), str(snum)],
        stdout_path=manual_column,
    )

    selected_lines: list[str] = []

    with manual_column.open("r", encoding="utf-8") as in_handle:
        with mc_column.open("w", encoding="utf-8") as out_handle:
            for raw_line in in_handle:
                line = raw_line.strip()
                if not line:
                    continue
                if "column" not in line:
                    continue

                fields = line.split()
                cid = int(fields[1])

                dash_num: int | None = None
                for field in fields:
                    if "-" in field:
                        dash_num = int(field.replace("-:", ""))
                        break

                if dash_num is None:
                    continue

                if dash_num == 0:
                    if site_r[1] != 0:
                        if site_r[0] <= cid <= site_r[1]:
                            selected_lines.append(line)
                    else:
                        selected_lines.append(line)

            out_c = math.ceil(sitec * float(len(selected_lines)))
            out_lines = selected_lines[:out_c]

            print(f"Newly added sites number: {len(out_lines)}/{len(selected_lines)}")

            for line in out_lines:
                out_handle.write(f"{line}\n")

    manual_column.unlink(missing_ok=True)

    with virstrain_build_temp.open("w", encoding="utf-8") as out_handle:
        if virstrain_build_column.exists():
            with virstrain_build_column.open("r", encoding="utf-8") as in_handle:
                shutil.copyfileobj(in_handle, out_handle)
        with mc_column.open("r", encoding="utf-8") as in_handle:
            shutil.copyfileobj(in_handle, out_handle)

    virstrain_build_column.unlink(missing_ok=True)
    mc_column.unlink(missing_ok=True)
    virstrain_build_temp.replace(virstrain_build_column)


def move_existing(files: list[str], target_dir: Path) -> None:
    """
    Move files that exist into the target directory.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    for file_name in files:
        src = Path(file_name)
        if src.exists():
            shutil.move(str(src), str(target_dir / src.name))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog="VirStrain_build.py", description=USAGE)
    parser.add_argument("-v", "--version", action="version", version="%(prog)s v1.17")
    parser.add_argument(
        "-i",
        "--input_msa",
        dest="input_msa",
        type=str,
        required=True,
        help="Input MSA file generated by mafft --- Required",
    )
    parser.add_argument(
        "-d",
        "--database_dir",
        dest="db_dir",
        type=str,
        default="VirStrain_DB",
        help="Database output dir (default: current workdir/VirStrain_DB)",
    )
    parser.add_argument(
        "-c",
        "--dash_cutoff",
        dest="dash_cutoff",
        type=float,
        default=0.0,
        help="The cutoff of dash in each column of MSA (default: 0)",
    )
    parser.add_argument(
        "-s",
        "--sites_ratio_cutoff",
        dest="sites_cutoff",
        type=float,
        default=0.0,
        help=(
            "The cutoff of sites number for manual-covering function "
            "(e.g. 1 means all useful sites will be used and 0.8 means 80%% useful sites will be used.)"
        ),
    )
    parser.add_argument(
        "-r",
        "--sites_range_cutoff",
        dest="sites_rcutoff",
        type=str,
        default=None,
        help=(
            "The cutoff of sites range for covering algorithm "
            "(e.g. 3-500 means the covering algorithm will only consider the SNV sites from 3-500 of MSA.)"
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    in_msa = Path(args.input_msa).resolve()
    db_dir = Path(args.db_dir).resolve()
    dashc = args.dash_cutoff
    sitec = args.sites_cutoff

    if args.sites_rcutoff is None:
        site_r = (0, 0)
    else:
        parts = args.sites_rcutoff.split("-")
        if len(parts) != 2:
            raise ValueError(
                f"Invalid --sites_range_cutoff format: {args.sites_rcutoff}. Expected start-end"
            )
        site_r = (int(parts[0]), int(parts[1]))

    if not in_msa.exists():
        raise FileNotFoundError(f"Input MSA file not found: {in_msa}")

    db_dir.mkdir(parents=True, exist_ok=True)

    # Start to build the database
    snum, cnum = scan_msa(in_msa)

    # Step 1 - Choose sites
    if site_r[1] == 0:
        run_cmd(
            [
                "perl",
                "bin/aln2cluster-overlap-kmer-withd.pl",
                str(in_msa),
                str(snum),
                str(dashc),
                "0",
                str(cnum),
                "0",
            ],
            stdout_path=Path("VirStrain_build.column"),
        )
    else:
        run_cmd(
            [
                "perl",
                "bin/aln2cluster-overlap-kmer-withd.pl",
                str(in_msa),
                str(snum),
                str(dashc),
                str(site_r[0]),
                str(site_r[1]),
                "0",
            ],
            stdout_path=Path("VirStrain_build.column"),
        )

    if sitec > 0:
        manual_covering(sitec, snum, in_msa, site_r)

    # Step 2 - Extract kmer and generate snp matrix
    run_cmd([sys.executable, "bin/S1_extract_kmer.py", "-i", str(in_msa), "-c", "VirStrain_build.column"])

    # Step 3 - Divide strains into clusters
    run_cmd([sys.executable, "bin/S2_remove_redundant_For_Me.py", "-i", "Strain_pos_snp_matrix_consider_all.txt"])

    # Step 4 - Hierarchical clustering
    run_cmd(
        [
            sys.executable,
            "bin/S2.5_Split_cls_hierarchical_with_perl.py",
            "-i",
            str(in_msa),
            "-r",
            "Remove_redundant_matrix_MM_Call.clstr",
        ]
    )

    move_existing(
        [
            "After_split.png",
            "Before_split.png",
            "ID2Name.txt",
        ],
        db_dir,
    )

    move_existing(
        [
            "Pos-snp-kmer-all.fa",
            "Pos-snp-kmer-all.txt",
            "Rebuild_cls.clstr",
            "Remove_redundant_matrix_MM_Call.clstr",
            "Strain_pos_snp_matrix_not_redundant_MM_Call.txt",
            "Strain_pos_snp_matrix_consider_all.txt",
            "SubCls_kmer.txt",
            "Strain_cls_info.txt",
            "VirStrain_build.column",
        ],
        db_dir,
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
